INSERT INTO AUTHOR (ID, NAME) VALUES (1, 'Ivanov');
INSERT INTO AUTHOR (ID, NAME) VALUES (2, 'Petrov');
INSERT INTO AUTHOR (ID, NAME) VALUES (3, 'Sidorov');
INSERT INTO AUTHOR (ID, NAME) VALUES (4, 'Pastuhov');

INSERT INTO GENRE (ID, NAME) VALUES (1, 'Comedy');
INSERT INTO GENRE (ID, NAME) VALUES (2, 'Drama');