spring:
  shell:
    interactive:
      enabled: false
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  banner:
    location: classpath:/banner.txt
  main:
    banner-mode: "off"
logging:
  level:
    ROOT: ERROR
    ru:
      otus:
        gpbu:
          mygena: DEBUG
