INSERT INTO setting (code, description, value) VALUES ('GENERATOR.GENERATE_REPOSITORIES', 'Gen to the repository for every entity', 'YES');
INSERT INTO setting (code, description, value) VALUES ('GENERATOR.GENERATE_ENTITIES', 'Gen to the repository for every entity', 'YES');
INSERT INTO setting (code, description, value) VALUES ('GENERATOR.PACKAGE.FOR_ENTITY', 'Java package for entity', 'ru.otus.gpbu.mygena.runtime.entity');
INSERT INTO setting (code, description, value) VALUES ('GENERATOR.PACKAGE.FOR_REPOSITORY', 'Java package for repository', 'ru.otus.gpbu.mygena.runtime.repository');
INSERT INTO setting (code, description, value) VALUES ('GENERATOR.PACKAGE.FOR_SHELL', 'Java package for shell commands', 'ru.otus.gpbu.mygena.runtime.shell');
INSERT INTO setting (code, description, value) VALUES ('GENERATOR.OUTPUT_DIR', 'Destination path', 'd:\temp\generate\');
INSERT INTO setting (code, description, value) VALUES ('GENERATOR.JOB.CHUNK_SIZE', 'Chunk size for job generate', '5');
INSERT INTO setting (code, description, value) VALUES ('GENERATOR.JOB.JPA_PAGING_ITEM_READER.PAGE_SIZE', 'Page size for JpaPagingItemReader', '10');
INSERT INTO setting (code, description, value) VALUES ('GENERATOR.JOB.JPA_PAGING_ITEM_READER.QUERY_STRING', 'QUERY STRING for JpaPagingItemReader', 'SELECT e FROM MyEntity e');

INSERT INTO setting (code, description, value) VALUES ('RUNTIME.ENVIRONMENT.TEMPLATE_FILE', '', 'runtime.zip');
INSERT INTO setting (code, description, value) VALUES ('RUNTIME.ENVIRONMENT.TEMPLATE_FILE_PATH', '', 'BOOT-INF/classes/');
INSERT INTO setting (code, description, value) VALUES ('RUNTIME.ENVIRONMENT.ARTIFACT_FILE_NAME', '', 'runtime-0.0.1-SNAPSHOT.jar');
INSERT INTO setting (code, description, value) VALUES ('RUNTIME.ENVIRONMENT.COMPILE.LOG_FILE', '', 'compile.log');
INSERT INTO setting (code, description, value) VALUES ('RUNTIME.ENVIRONMENT.COMPILE.OPEN_COMPILE_WINDOW', '', 'YES');
INSERT INTO setting (code, description, value) VALUES ('RUNTIME.ENVIRONMENT.COMPILE.MAVEN_SKIP_TESTS', '', 'YES');
INSERT INTO setting (code, description, value) VALUES ('RUNTIME.ENVIRONMENT.COMPILE.MAVEN_BUILD_OPTIONS', '', 'package -T 1C -o -am');

INSERT INTO entity (code, description) VALUES ('Person', 'Person');
INSERT INTO entity (code, description) VALUES ('Customer', 'Customer');
INSERT INTO entity (code, description) VALUES ('Loan', 'Loan');
INSERT INTO entity (code, description) VALUES ('Entity4', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity5', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity6', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity7', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity8', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity9', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity10', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity11', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity12', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity13', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity14', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity15', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity16', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity17', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity18', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity19', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity20', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity21', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity22', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity23', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity24', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity25', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity26', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity27', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity28', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity29', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity30', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity31', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity32', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity33', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity34', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity35', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity36', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity37', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity38', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity39', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity40', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity41', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity42', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity43', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity44', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity45', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity46', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity47', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity48', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity49', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity50', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity51', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity52', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity53', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity54', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity55', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity56', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity57', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity58', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity60', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity61', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity62', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity63', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity64', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity65', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity66', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity67', 'EntityDescription3');
INSERT INTO entity (code, description) VALUES ('Entity68', 'EntityDescription1');
INSERT INTO entity (code, description) VALUES ('Entity69', 'EntityDescription2');
INSERT INTO entity (code, description) VALUES ('Entity70', 'EntityDescription3');


INSERT INTO entity_attr (code, description, type, entity_id) VALUES ('firstName', 'Firstname', 'String', 1);
INSERT INTO entity_attr (code, description, type, entity_id) VALUES ('lastName', 'Lastname', 'String', 1);
INSERT INTO entity_attr (code, description, type, entity_id) VALUES ('age', 'AttributeDescription2', 'Long', 1);

INSERT INTO entity_attr (code, description, type, entity_id) VALUES ('Attribute3', 'AttributeDescription3', 'String', 2);
INSERT INTO entity_attr (code, description, type, entity_id) VALUES ('Attribute4', 'AttributeDescription4', 'Long', 2);
INSERT INTO entity_attr (code, description, type, entity_id) VALUES ('Attribute5', 'AttributeDescription4', 'String', 2);

INSERT INTO entity_attr (code, description, type, entity_id) VALUES ('code', 'code', 'String', 3);
INSERT INTO entity_attr (code, description, type, entity_id) VALUES ('description', 'AttributeDescription7', 'String', 3);
